# -*- coding: utf-8 -*-
# Code generated by:')
# author: jieshukai
# Date: {{ date }}
# Database: {{ db_name }}
# Peewee version: {{ __version__ }}

from peewee import *

database = {{ db_class }}('{{ db_name }}', **{{ db_config }})


class BaseModel(Model):
    class Meta:
        database = database

{% for table in tables %}
class {{ make_model_name(table) }}Model(BaseModel):
    {% for  column in maeke_model_columns(table) %}{{ column }}
    {% endfor %}

    class Meta:
        db_table = '{{ table }}'
{% endfor %}

{{ db_name }} = {{ all_model }}
